title: "Grav Demo"
default_lang: de
author:
  name: Nicholas Krebs
  email: "contact@chraebsli.dev"
taxonomies:
  - category
  - tag
metadata:
  description: "Diese Seite dient als inoffizielle Demonstration und Hilfestellung für Grav"
summary:
  enabled: true
  format: short
  size: 300
  delimiter: "==="
redirects: null
routes: null
blog:
  route: /tutorial
