streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        "": [user/themes/quark-child, user/themes/quark]
production-mode: true
grid-size: grid-md
header-fixed: false
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark-child/images/logo/logo-150px.png:
    name: logo-300px.png
    full_path: logo-300px.png
    type: image/png
    size: 32904
    path: user/themes/quark-child/images/logo/logo-300px.png
custom_logo_mobile:
  user/themes/quark-child/images/logo/logo-150px.png:
    name: logo-300px.png
    full_path: logo-300px.png
    type: image/png
    size: 32904
    path: user/themes/quark-child/images/logo/logo-300px.png
